# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [ "kvm-amd" ];

  fileSystems."/" =
    { device = "none";
      fsType = "tmpfs";
      neededForBoot = true;
      options = [ "defaults" "size=8G" "mode=755" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-id/nvme-CT4000P3PSSD8_2325E6E63746-part1";
      fsType = "vfat";
      neededForBoot = true;
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-id/nvme-CT4000P3PSSD8_2325E6E63746-part2";
      fsType = "bcachefs";
      neededForBoot = true;
      options = [ "noatime" "nodiratime" ];
    };

  fileSystems."/data" =
    { device = "/dev/disk/by-id/nvme-CT4000P3PSSD8_2325E6E63746-part3";
      fsType = "bcachefs";
      neededForBoot = true;
      options = [ "noatime" "nodiratime" ];
    };

  fileSystems."/home" =
    { device = "/data/home";
      fsType = "none";
      neededForBoot = true;
      options = [ "bind" ];
      depends = [ "/data" ];
    };

  fileSystems."/root" =
    { device = "/data/root";
      fsType = "none";
      neededForBoot = true;
      options = [ "bind" ];
      depends = [ "/data" ];
    };

  fileSystems."/etc/nixos" =
    { device = "/data/nixos/mini";
      fsType = "none";
      neededForBoot = true;
      options = [ "bind" ];
      depends = [ "/data" ];
    };

  fileSystems."/home/cullmann/vms" =
    { device = "/dev/disk/by-id/ata-CT2000MX500SSD1_2138E5D5061F";
      fsType = "bcachefs";
      neededForBoot = true;
      options = [ "noatime" "nodiratime" ];
      depends = [ "/home" ];
    };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
