# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [ "kvm-amd" ];

  # don't check for split locks, for KVM and Co.
  boot.kernelParams = [ "split_lock_detect=off" ];

  # system
  boot.initrd.luks.devices."crypt-system".device = "/dev/disk/by-id/nvme-CT4000P3PSSD8_2325E6E63746-part2";

  # efi partition
  fileSystems."/boot" =
    { device = "/dev/disk/by-id/nvme-CT4000P3PSSD8_2325E6E63746-part1";
      fsType = "vfat";
      neededForBoot = true;
    };

  # vms
  boot.initrd.luks.devices."crypt-vms".device = "/dev/disk/by-id/ata-CT2000MX500SSD1_2138E5D5061F";
  fileSystems."/home/cullmann/vms" =
    { device = "/dev/mapper/crypt-vms";
      fsType = "btrfs";
      neededForBoot = true;
      options = [ "noatime" "nodiratime" ];
      depends = [ "/home" ];
    };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
